services:
  postgres:
    image: bitnami/postgresql:17.6.0
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d main"]
      interval: 5s
      timeout: 3s
      retries: 3

  redis:
    image: redis:alpine3.20
    container_name: redis_db
    command: ["redis-server", "--requirepass", "redis123"]
    ports:
      - "6389:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis123", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  api:
    image: phamgiaphuc/dev-go-apis:1.0.0
    container_name: apis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      PORT: ${PORT}
      SERVER_URL: ${SERVER_URL}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      ACCESS_TOKEN_TTL: ${ACCESS_TOKEN_TTL}
      REFRESH_TOKEN_TTL: ${REFRESH_TOKEN_TTL}
      MIGRATION_MODE: ${MIGRATION_MODE}
    ports:
      - ${PORT}:${PORT}

volumes:
  pgdata:
  redisdata:
