// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package emails

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func EmailVerification(fullName string, verifyLink string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>Welcome back to Acus Dev</title></head><body style=\"margin:0;padding:0;background-color:#f5f5f5;font-family:Arial, sans-serif;\"><table role=\"presentation\" width=\"100%\" style=\"max-width:720px;background-color:#ffffff;margin:0 auto\"><tr><td style=\"padding:36px;\"><p style=\"font-weight:600;font-size:18px;margin:0 0 20px 0;\">Hi, ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fullName)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/emails/email-verification.templ`, Line: 15, Col: 81}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</p><p style=\"color:#525252;font-size:14px;margin:0 0 20px 0;\">Welcome to Acus Dev! We're very excited to have you on board.</p><p style=\"color:#525252;font-size:14px;margin:0 0 20px 0;\">To verify your account, please click the link below and the link will remain active for 5 minutes:</p><a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 templ.SafeURL
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinURLErrs(verifyLink)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/emails/email-verification.templ`, Line: 23, Col: 24}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" target=\"_blank\" style=\"display:inline-block;text-decoration:none;background-color:#2563eb;color:#ffffff;font-size:14px;line-height:40px;padding:0 16px;margin:0 0 20px 0;\">Confirm your account</a><p style=\"color:#525252;font-size:14px;margin:20px 0 20px 0;\">Need help, or have questions? Please contact our support service via <a href=\"mailto:support@mail.acusdev.com\" style=\"color:#2563eb;text-decoration:none;\">support@mail.acusdev.com</a></p><p style=\"color:#525252;font-size:14px;margin:20px 0 0 0;\">Yours truly,</p><p style=\"color:#525252;font-size:14px;margin:2px 0 0 0;\">Acus Dev Team</p></td></tr></table></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
